plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "java"
}

group = project.maven_group
version = project.mod_version
base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        events "failed", "skipped"
    }
}

jar {
    from("README.md") {
        into "META-INF"
    }
}