plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "java"
}

group = project.maven_group
version = project.mod_version
base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        url = "https://maven.fabricmc.net/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    testImplementation platform("org.junit:junit-bom:5.12.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
    testLogging {
        events "failed", "skipped"
    }
}

jar {
    from("README.md") {
        into "META-INF"
    }
}
